# 站点配置文件
# 定义要爬取的网站和对应的选择器规则

sites:
  # 示例网站1 - 新闻网站
  - name: "示例新闻网站"
    base_url: "https://example-news.com"
    description: "示例新闻网站爬虫配置"
    enabled: true
    
    # 起始URL列表
    start_urls:
      - "https://example-news.com"
      - "https://example-news.com/category/tech"
      - "https://example-news.com/category/business"
    
    # CSS选择器配置
    selectors:
      title: "h1.article-title, .headline, .post-title"
      content: ".article-content, .post-content, .content"
      description: ".article-summary, .excerpt, .summary"
      author: ".author-name, .by-author, .author"
      publish_date: ".publish-date, .date, time"
      tags: ".tags a, .tag, .category"
      links: "a[href]"
      images: ".article-content img[src]"
      next_page: ".pagination .next, .next-page"
      article_list: ".article-list .article-item"
    
    # 爬取规则
    rules:
      max_depth: 3
      max_pages: 500
      respect_robots: true
      allowed_domains:
        - "example-news.com"
        - "cdn.example-news.com"
      url_patterns:
        - ".*/article/.*"
        - ".*/news/.*"
        - ".*/\\d{4}/\\d{2}/\\d{2}/.*"
      content_types:
        - "text/html"

  # 示例网站2 - 博客网站
  - name: "示例博客网站"
    base_url: "https://example-blog.com"
    description: "示例博客网站爬虫配置"
    enabled: true
    
    start_urls:
      - "https://example-blog.com/blog"
      - "https://example-blog.com/latest"
    
    selectors:
      title: "h1.post-title, .entry-title"
      content: ".post-content, .entry-content"
      description: ".post-excerpt, .entry-summary"
      author: ".post-author, .author-info .name"
      publish_date: ".post-date, .published-date"
      tags: ".post-tags a, .tag-list a"
      links: ".post-content a[href]"
      images: ".post-content img[src]"
      next_page: ".pagination .next"
      article_list: ".blog-posts .post-item"
    
    rules:
      max_depth: 2
      max_pages: 200
      respect_robots: true
      allowed_domains:
        - "example-blog.com"
      url_patterns:
        - ".*/blog/.*"
        - ".*/post/.*"
      content_types:
        - "text/html"

  # 示例网站3 - 电商网站
  - name: "示例电商网站"
    base_url: "https://example-shop.com"
    description: "示例电商网站产品信息爬虫"
    enabled: false  # 默认禁用
    
    start_urls:
      - "https://example-shop.com/products"
      - "https://example-shop.com/categories"
    
    selectors:
      title: "h1.product-title, .product-name"
      content: ".product-description, .product-details"
      description: ".product-summary, .short-description"
      price: ".price, .product-price, .current-price"
      images: ".product-gallery img[src], .product-images img[src]"
      rating: ".rating, .product-rating"
      reviews: ".reviews-count, .review-count"
      category: ".breadcrumb a, .category-name"
      specs: ".specifications, .product-specs"
      next_page: ".pagination .next"
      product_list: ".product-grid .product-item"
    
    rules:
      max_depth: 2
      max_pages: 1000
      respect_robots: true
      allowed_domains:
        - "example-shop.com"
        - "cdn.example-shop.com"
      url_patterns:
        - ".*/product/.*"
        - ".*/p/.*"
      content_types:
        - "text/html"

  # 示例网站4 - 论坛网站
  - name: "示例论坛网站"
    base_url: "https://example-forum.com"
    description: "示例论坛网站爬虫配置"
    enabled: false
    
    start_urls:
      - "https://example-forum.com/forums"
      - "https://example-forum.com/latest-posts"
    
    selectors:
      title: "h1.topic-title, .thread-title"
      content: ".post-content, .message-content"
      description: ".post-excerpt, .message-preview"
      author: ".author-name, .post-author"
      publish_date: ".post-date, .message-date"
      tags: ".topic-tags a, .thread-tags a"
      links: ".post-content a[href]"
      images: ".post-content img[src]"
      replies: ".reply-count, .post-count"
      views: ".view-count, .views"
      next_page: ".pagination .next"
      post_list: ".topic-list .topic-item"
    
    rules:
      max_depth: 2
      max_pages: 300
      respect_robots: true
      allowed_domains:
        - "example-forum.com"
      url_patterns:
        - ".*/topic/.*"
        - ".*/thread/.*"
        - ".*/post/.*"
      content_types:
        - "text/html"

  # 示例网站5 - 学术网站
  - name: "示例学术网站"
    base_url: "https://example-academic.com"
    description: "示例学术网站论文爬虫"
    enabled: false
    
    start_urls:
      - "https://example-academic.com/papers"
      - "https://example-academic.com/journals"
    
    selectors:
      title: "h1.paper-title, .article-title"
      content: ".abstract, .paper-content"
      description: ".paper-summary, .abstract"
      author: ".authors, .author-list"
      publish_date: ".publication-date, .published"
      tags: ".keywords, .tags"
      links: ".references a[href]"
      images: ".figures img[src]"
      doi: ".doi, .paper-doi"
      journal: ".journal-name, .publication"
      citation: ".citation-count, .citations"
      next_page: ".pagination .next"
      paper_list: ".paper-list .paper-item"
    
    rules:
      max_depth: 2
      max_pages: 500
      respect_robots: true
      allowed_domains:
        - "example-academic.com"
      url_patterns:
        - ".*/paper/.*"
        - ".*/article/.*"
        - ".*/doi/.*"
      content_types:
        - "text/html"
        - "application/pdf"

# 全局规则配置
global_rules:
  # 默认请求头
  default_headers:
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    Accept-Language: "zh-CN,zh;q=0.9,en;q=0.8"
    Accept-Encoding: "gzip, deflate"
    Connection: "keep-alive"
    Upgrade-Insecure-Requests: "1"
  
  # 通用CSS选择器
  common_selectors:
    # 文章内容常见选择器
    article_content:
      - "article"
      - ".article"
      - ".post"
      - ".content"
      - ".main-content"
      - ".entry-content"
      - ".post-content"
      - ".article-content"
    
    # 标题常见选择器
    title:
      - "h1"
      - "title"
      - ".title"
      - ".headline"
      - ".post-title"
      - ".article-title"
      - ".entry-title"
    
    # 时间常见选择器
    datetime:
      - "time"
      - ".date"
      - ".time"
      - ".datetime"
      - ".published"
      - ".post-date"
      - ".publish-date"
      - ".article-date"
    
    # 作者常见选择器
    author:
      - ".author"
      - ".by-author"
      - ".post-author"
      - ".article-author"
      - ".writer"
      - ".author-name"
  
  # 需要排除的URL模式
  excluded_patterns:
    - ".*\\.css$"
    - ".*\\.js$"
    - ".*\\.jpg$"
    - ".*\\.png$"
    - ".*\\.gif$"
    - ".*\\.ico$"
    - ".*\\.pdf$"
    - ".*\\.doc$"
    - ".*\\.xls$"
    - ".*/login.*"
    - ".*/register.*"
    - ".*/admin.*"
    - ".*/user.*"
    - ".*/profile.*"
    - ".*/cart.*"
    - ".*/checkout.*"
    - ".*/search.*"
    - ".*/api/.*"
  
  # 需要跳过的文件类型
  skip_file_types:
    - "application/javascript"
    - "text/css"
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "image/webp"
    - "application/pdf"
    - "application/octet-stream"
    - "video/mp4"
    - "audio/mp3" 